// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTodoList.Application.Infrastructure;

namespace MultiTodoList.Application.Migrations
{
    [DbContext(typeof(MultiTodoListDbContext))]
    [Migration("20190524214459_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MultiTodoList.Application.Infrastructure.Dto.TodoDbDto", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Complited");

                    b.Property<DateTime>("Created");

                    b.Property<string>("GroupName")
                        .IsRequired();

                    b.Property<bool>("IsComplited");

                    b.HasKey("Name");

                    b.HasIndex("GroupName");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("MultiTodoList.Application.Infrastructure.Dto.TodoGroupDbDto", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Blue");

                    b.Property<byte>("Green");

                    b.Property<byte>("Red");

                    b.Property<Guid>("UserId");

                    b.HasKey("Name");

                    b.HasIndex("UserId");

                    b.ToTable("TodoGroups");
                });

            modelBuilder.Entity("MultiTodoList.Application.Infrastructure.Dto.UserDbDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Age");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<byte[]>("Photo");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MultiTodoList.Application.Infrastructure.Dto.TodoDbDto", b =>
                {
                    b.HasOne("MultiTodoList.Application.Infrastructure.Dto.TodoGroupDbDto", "Group")
                        .WithMany("Todos")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MultiTodoList.Application.Infrastructure.Dto.TodoGroupDbDto", b =>
                {
                    b.HasOne("MultiTodoList.Application.Infrastructure.Dto.UserDbDto", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
